package com.dashieapp.Dashie.halite.voice.speakerid

import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.ln
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sin

/**
 * Kaldi-compatible 80-dim log-mel filterbank frontend for speaker embeddings.
 *
 * Byte-matches torchaudio.compliance.kaldi.fbank(num_mel_bins=80,
 * frame_length=25, frame_shift=10, dither=0.0, sample_frequency=16000,
 * window_type="hamming", use_energy=False) — the exact featurization the
 * WeSpeaker ResNet34 ONNX model was validated with in the benchmark harness
 * (wake-word-training/speaker-id/). Parity is enforced by
 * KaldiFbankParityTest against a fixture generated by
 * generate_parity_fixtures.py; do not change constants without regenerating.
 *
 * Input is 16 kHz mono PCM16; internal math is Double to match the numpy
 * reference within float precision.
 */
object KaldiFbank {
    const val SAMPLE_RATE = 16000
    const val NUM_BINS = 80
    private const val FRAME_LEN = 400   // 25 ms
    private const val FRAME_SHIFT = 160 // 10 ms
    private const val NFFT = 512
    private const val FFT_BINS = NFFT / 2 // nyquist bin dropped, kaldi-style
    private const val PREEMPHASIS = 0.97
    private const val LOG_FLOOR = 1.1921e-07 // float eps, kaldi log floor

    private val window = DoubleArray(FRAME_LEN) { n ->
        0.54 - 0.46 * cos(2.0 * PI * n / (FRAME_LEN - 1))
    }

    // Triangular mel filterbank, 80 bins, 20 Hz..nyquist, kaldi mel scale
    private val melBanks: Array<DoubleArray> = run {
        val melLow = hzToMel(20.0)
        val melHigh = hzToMel(SAMPLE_RATE / 2.0)
        val melDelta = (melHigh - melLow) / (NUM_BINS + 1)
        val fftMels = DoubleArray(FFT_BINS) { i ->
            hzToMel(i.toDouble() * SAMPLE_RATE / NFFT)
        }
        Array(NUM_BINS) { b ->
            val left = melLow + b * melDelta
            val center = left + melDelta
            val right = center + melDelta
            DoubleArray(FFT_BINS) { i ->
                val up = (fftMels[i] - left) / (center - left)
                val down = (right - fftMels[i]) / (right - center)
                max(0.0, min(up, down))
            }
        }
    }

    private fun hzToMel(hz: Double): Double = 1127.0 * ln(1.0 + hz / 700.0)

    /** Number of frames produced for [numSamples] input samples (snip_edges). */
    fun numFrames(numSamples: Int): Int =
        if (numSamples < FRAME_LEN) 0 else 1 + (numSamples - FRAME_LEN) / FRAME_SHIFT

    /**
     * PCM16 -> log-mel features, one FloatArray(80) per frame.
     * @param applyCmn subtract the per-utterance mean of each coefficient
     *                 (cepstral mean normalization) — required by WeSpeaker.
     */
    fun extract(pcm: ShortArray, applyCmn: Boolean = true): Array<FloatArray> {
        val frames = numFrames(pcm.size)
        if (frames == 0) return emptyArray()

        val feats = Array(frames) { FloatArray(NUM_BINS) }
        val frame = DoubleArray(FRAME_LEN)
        val re = DoubleArray(NFFT)
        val im = DoubleArray(NFFT)

        for (f in 0 until frames) {
            val start = f * FRAME_SHIFT
            var mean = 0.0
            for (i in 0 until FRAME_LEN) {
                frame[i] = pcm[start + i].toDouble()
                mean += frame[i]
            }
            mean /= FRAME_LEN
            for (i in 0 until FRAME_LEN) frame[i] -= mean // remove_dc_offset

            // preemphasis (kaldi: x[0] -= coeff * x[0])
            for (i in FRAME_LEN - 1 downTo 1) {
                frame[i] -= PREEMPHASIS * frame[i - 1]
            }
            frame[0] -= PREEMPHASIS * frame[0]

            for (i in 0 until FRAME_LEN) frame[i] *= window[i]

            java.util.Arrays.fill(re, 0.0)
            java.util.Arrays.fill(im, 0.0)
            System.arraycopy(frame, 0, re, 0, FRAME_LEN)
            fftInPlace(re, im)

            for (b in 0 until NUM_BINS) {
                val bank = melBanks[b]
                var acc = 0.0
                for (i in 0 until FFT_BINS) {
                    if (bank[i] != 0.0) {
                        acc += bank[i] * (re[i] * re[i] + im[i] * im[i])
                    }
                }
                feats[f][b] = ln(max(acc, LOG_FLOOR)).toFloat()
            }
        }

        if (applyCmn) {
            for (b in 0 until NUM_BINS) {
                var mean = 0.0
                for (f in 0 until frames) mean += feats[f][b]
                mean /= frames
                for (f in 0 until frames) {
                    feats[f][b] = (feats[f][b] - mean).toFloat()
                }
            }
        }
        return feats
    }

    /** Iterative radix-2 Cooley-Tukey FFT, in place. Sizes are powers of 2. */
    private fun fftInPlace(re: DoubleArray, im: DoubleArray) {
        val n = re.size
        // bit-reversal permutation
        var j = 0
        for (i in 0 until n - 1) {
            if (i < j) {
                var t = re[i]; re[i] = re[j]; re[j] = t
                t = im[i]; im[i] = im[j]; im[j] = t
            }
            var m = n shr 1
            while (j >= m && m > 0) {
                j -= m
                m = m shr 1
            }
            j += m
        }
        var len = 2
        while (len <= n) {
            val ang = -2.0 * PI / len
            val wRe = cos(ang)
            val wIm = sin(ang)
            var i = 0
            while (i < n) {
                var curRe = 1.0
                var curIm = 0.0
                for (k in 0 until len / 2) {
                    val aRe = re[i + k]
                    val aIm = im[i + k]
                    val bRe = re[i + k + len / 2] * curRe - im[i + k + len / 2] * curIm
                    val bIm = re[i + k + len / 2] * curIm + im[i + k + len / 2] * curRe
                    re[i + k] = aRe + bRe
                    im[i + k] = aIm + bIm
                    re[i + k + len / 2] = aRe - bRe
                    im[i + k + len / 2] = aIm - bIm
                    val nRe = curRe * wRe - curIm * wIm
                    curIm = curRe * wIm + curIm * wRe
                    curRe = nRe
                }
                i += len
            }
            len = len shl 1
        }
    }

    /** Rough speech-energy check used by enrollment quality gating. */
    fun meanAbsAmplitude(pcm: ShortArray): Double {
        if (pcm.isEmpty()) return 0.0
        var acc = 0.0
        for (s in pcm) acc += abs(s.toInt()).toDouble()
        return acc / pcm.size
    }
}
