package com.dashieapp.Dashie.halite.settings.schemas

/*
 * GENERATED — DO NOT EDIT BY HAND
 *
 * Source of truth:
 *   dashieapp_staging/js/data/settings/engine-resolution.js
 * Generated by:
 *   dashieapp_staging/scripts/gen-android-engine-resolver.mjs
 *
 * Edit the source, re-run the generator, and commit every output together.
 * `npm run lint:engine-resolver` fails the build if any copy drifted.
 */

/**
 * How a saved local engine resolves into the flat settings the runtime reads.
 *
 * The console's Local Engines registry is the source of the engine LIST; this is the
 * mapping from "the user picked engine X" to the keys that actually drive the pipeline.
 * Both sides must agree, so both are generated from one JS canonical.
 */
object EngineResolver {

    /** The flat keys one engine kind writes. [modelKey] is null for kinds with no model axis. */
    data class Spec(
        val providerKey: String,
        val providerValue: String,
        val urlKey: String,
        val modelKey: String?
    )

    /** Engine kind id -> its resolution spec. */
    val SPECS: Map<String, Spec> = mapOf(
        "tts" to Spec(
            providerKey = "voice.ttsProvider",
            providerValue = "local_url",
            urlKey = "voice.localTtsUrl",
            modelKey = null
        ),
        "stt" to Spec(
            providerKey = "voice.sttProvider",
            providerValue = "local_stt_url",
            urlKey = "voice.localSttUrl",
            modelKey = null
        ),
        "llm" to Spec(
            providerKey = "ai.model",
            providerValue = "local",
            urlKey = "voice.localLlmUrl",
            modelKey = "voice.localLlmModel"
        )
    )

    fun spec(kind: String): Spec? = SPECS[kind]

    /**
     * The [key, value] pairs selecting [url]/[model] for [kind] must write.
     * Empty when the kind is unknown — callers should treat that as "do nothing"
     * rather than writing a partial pipeline.
     */
    fun resolveToSettings(kind: String, url: String, model: String = ""): List<Pair<String, String>> {
        val s = spec(kind) ?: return emptyList()
        val pairs = mutableListOf(
            s.providerKey to s.providerValue,
            s.urlKey to url
        )
        s.modelKey?.let { pairs.add(it to model) }
        return pairs
    }
}
