package com.dashieapp.Dashie.halite.voice.speakerid

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import kotlin.math.abs

/**
 * Parity test for the Kotlin kaldi-fbank port against the Python reference.
 *
 * Fixture (speakerid/parity_fixture_resnet34.json) is generated by
 * wake-word-training/speaker-id/generate_parity_fixtures.py from a
 * deterministic synthetic signal, containing torchaudio's fbank output for
 * the exact parameters the WeSpeaker ResNet34 model expects. If this test
 * fails after a KaldiFbank change, the embeddings will be garbage on-device
 * — the wake-word MFE effort taught us to gate this in CI, not on-device.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class KaldiFbankParityTest {

    private val fixture: JSONObject by lazy {
        val stream = javaClass.classLoader!!
            .getResourceAsStream("speakerid/parity_fixture_resnet34.json")!!
        JSONObject(stream.bufferedReader().readText())
    }

    private fun pcm(): ShortArray {
        val arr = fixture.getJSONArray("pcm16")
        return ShortArray(arr.length()) { arr.getInt(it).toShort() }
    }

    private fun frame(name: String): FloatArray {
        val arr = fixture.getJSONArray(name)
        return FloatArray(arr.length()) { arr.getDouble(it).toFloat() }
    }

    @Test
    fun shapeMatchesReference() {
        val feats = KaldiFbank.extract(pcm())
        val shape = fixture.getJSONArray("fbank_shape")
        assertEquals(shape.getInt(0), feats.size)
        assertEquals(shape.getInt(1), feats[0].size)
    }

    @Test
    fun framesMatchReferenceWithinFloatPrecision() {
        val feats = KaldiFbank.extract(pcm())
        val checks = mapOf(
            0 to frame("fbank_frame_0"),
            feats.size / 2 to frame("fbank_frame_mid"),
            feats.size - 1 to frame("fbank_frame_last"),
        )
        for ((idx, expected) in checks) {
            var maxDiff = 0.0
            for (b in expected.indices) {
                maxDiff = maxOf(maxDiff, abs(feats[idx][b] - expected[b]).toDouble())
            }
            assertTrue(
                "frame $idx max |Δ| = $maxDiff (limit 2e-3)",
                maxDiff < 2e-3
            )
        }
    }

    @Test
    fun fullMatrixChecksumsMatch() {
        val feats = KaldiFbank.extract(pcm())
        var sum = 0.0
        var absSum = 0.0
        for (f in feats) for (v in f) {
            sum += v
            absSum += abs(v)
        }
        // CMN makes the plain sum ~0 by construction; abs-sum is the real check
        assertTrue("post-CMN sum should be ~0, was $sum", abs(sum) < 1.0)
        val expectedAbs = fixture.getDouble("fbank_abs_sum")
        val relDiff = abs(absSum - expectedAbs) / expectedAbs
        assertTrue(
            "abs-sum rel diff $relDiff (limit 1e-4): $absSum vs $expectedAbs",
            relDiff < 1e-4
        )
    }

    @Test
    fun numFramesSnipEdgesSemantics() {
        assertEquals(0, KaldiFbank.numFrames(399))
        assertEquals(1, KaldiFbank.numFrames(400))
        assertEquals(1, KaldiFbank.numFrames(559))
        assertEquals(2, KaldiFbank.numFrames(560))
        assertEquals(198, KaldiFbank.numFrames(32000))
    }
}
